import Head from 'next/head'
import Header from '../components/Header'
import Sidebar from '../components/Sidebar'
import Login from '../components/Login'
import { getSession } from 'next-auth/react'
import Feed from '../components/Feed'

export default function Home({session}) {
  if(!session) return <Login/>
  return (
    <div>
      <Head>
        <title>Facebook clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className="flex bg-gray-100">
       {/* Left Side bar */}
       <Sidebar/>
       {/* Feed (Create post and posts) */}
       <Feed/>
       {/* Right side bar */}
      </main>

    </div>
  )
}

export async function getServerSideProps(context){
  const session = await getSession(context) ;
  return{
    props: {session},
  }
}
